export const DUMMY_NEWS = [
  {
    id: 1,
    tag: "Biz",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/bomb.jpg",
    imgCaption: "World is shock to realize what Israel capable of",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title: "Your Phone Won't Be the Next Exploding Pager",
    content:
      "<p>For two days this week, Hezbollah has been rocked by a series of small explosions across Lebanon, injuring thousands and killing at least 25. But these attacks haven't come from rockets or drones. Instead, they've resulted from boobytrapped electronics—including pagers, walkie-talkies, and even, reportedly, solar equipment—detonating in coordinated waves. As details come into view of the elaborate supply chain attack that compromised these devices, citizens on the ground in Lebanon and people around the world are questioning whether such attacks could target any device in your pocket.</p><p>The campaign to compromise key Hezbollah communication infrastructure with explosives was clearly elaborate and involved. The operation, which is widely believed to have been perpetrated by Israel, goes far beyond past examples of hardware supply chain attacks and may be a source of inspiration for future spycraft around the world. But sources tell WIRED that the specific scale and scope of the effort would not be easily replicated in other contexts. And, more broadly, the resources and precision involved in carrying out such an attack would be prohibitively difficult to maintain over time for key consumer devices like smartphones—which are used so widely and regularly scrutinized by researchers, product testers, and repair technicians.</p><p>“I do think there is absolutely potential to see more of this in the longer term, not targeting civilians, but generally targeting other military actors,” says Zachary Kallenborn, an adjunct nonresident fellow with the Center for Strategic and International Studies. Kallenborn says militaries are increasingly relying on commercial technology—from drones to communications devices—all of which could be compromised if supply chains can be exploited by adversaries. “These systems are being sourced from all over the globe,” he says. “What that means, then, is that you also have these global supply chains supporting them.”</p>",
    readCount: 448,
    commentCount: 3,
    path: "1-your-phone-won-t-be-the-next-exploding-pager",
  },
  {
    id: 2,
    tag: "Biz",
    datetime: "2024/09/16 08:52",
    imgUrl: "/img/movie.jpg",
    imgCaption: "Step up your smartphone game by creating movie",
    imgCredit: "Pexels",
    writer: "Micah Bell",
    writerImg: "/img/user.jpg",
    title:
      "28 Years Later: Danny Boyle's New Zombie Flick Was Shot on an iPhone 15",
    content:
      "<p>Even though professional, cinema-quality digital cameras are now commonplace, they're generally not small or compact. (Take a look at Arri's current lineup, for example, with its Mini LF, used to capture Deadpool & Wolverine.) However, Danny Boyle's forthcoming zombie flick, 28 Years Later, was shot over the summer with a bunch of adapted iPhone 15s, WIRED has learned, making the Hollywood thriller, with its budget of $75 million, the biggest movie to date filmed with smartphones.</p><p>Starring Killing Eve's Jodie Comer, next James Bond favorite Aaron Taylor-Johnson, and Ralph Fiennes, 28 Years Later, due for release in June 2025, is the long-awaited follow-up to 28 Days Later—the 2002 genre-defining movie that was the first to portray zombies as scary fast rather than lumbering—and 2007's 28 Weeks Later. Boyle is joined by cinematographer Anthony Dod Mantle; they won Oscars together in 2009 for their hit Slumdog Millionaire. Mantle was also cinematographer on the original 28 Days Later, as well as Boyle's films Trance (2013), T2 Trainspotting (2017), and 127 Hours (2010).</p><p>There's a tech story arc to Boyle and Mantle choosing Apples log-profile powerhouse for 28 Years Later: The pairs 2002 kick-off movie, 28 Days Later, was filmed with an innovative-for-the-time digital camera—one of the first Hollywood feature films shot with a Canon XL-1. The lust-worthy $4,000 prosumer camcorder had interchangeable lenses and wrote data to MiniDV (digital video) tapes.</p>",
    readCount: 753,
    commentCount: 3,
    path: "2-28-years-later-danny-boyle-s-new-zombie-flick-was-shot-on-an-iphone-15",
  },
  {
    id: 3,
    tag: "Biz",
    datetime: "2024/09/21 02:43",
    imgUrl: "/img/iphone.jpg",
    imgCaption: "Ios 18 join the GEN AI force",
    imgCredit: "Apple",
    writer: "Dutch Van der Linde",
    writerImg: "/img/user.jpg",
    title: "The Top New Features in Apple's iOS 18 and iPadOS 18",
    content:
      "<p>Apple executives always describe new hardware and software as the “best” or “biggest” ever, but the delivery doesn't usually live up to the hype (see the recent iPads). However, iOS 18 and iPadOS 18 might be deserving of a few of those adjectives. The new operating systems, which are now available, have the usual degree of year-over-year quality-of-life improvements, but Apple Intelligence stole the show.</p><p>Before installing the new operating system, I highly recommend you back up your devices. You can do this via iCloud—go to Settings, tap on your name at the top, and select iCloud. Then, tap on iCloud Backup, toggle it on, and tap Back Up Now to start a new backup. On the previous iCloud page, you also have the option to toggle off certain apps that you don't want to include in the backup. Don't have enough iCloud storage, or want to use another method? Check out our How to Back Up Your iPhone or iPad guide for alternative options.</p><p>Once you've backed up, you're ready to install iOS 18. Since this is a hefty update, you should plug your devices into a charger and ensure they're connected to Wi-Fi before the update starts. Now go to Settings > General > Software Update. You'll see the option to download the update. Tap Download and Install and, when the download is done, tap Install Now to start the update. You'll know the update is complete when your device restarts.</p>",
    readCount: 1067,
    commentCount: 3,
    path: "3-the-top-new-features-in-apple-s-ios-18-and-ipados-18",
  },
  {
    id: 4,
    tag: "Biz",
    datetime: "2024/09/09 07:45",
    imgUrl: "/img/meta.jpg",
    imgCaption: "Biggest Meta conference incoming",
    imgCredit: "Facebook",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title: "Meta Connect Starts Wednesday. Here's What to Expect",
    content:
      "<p>Meta Connect, the big developer event and hardware showcase from the company that runs Facebook and Instagram, is kicking off next week. Meta is likely to show off its new VR and mixed-reality technology, put a shiny polish on its meandering metaverse ambitions, and delve into all the fresh ways it plans to squeeze artificial intelligence into every crevice of its devices and services.</p><p>The event takes place on Wednesday September 25, starting at 10 am Pacific time. The keynote address, where most of the new stuff will be announced, will be livestreamed. The host for the event will be Meta CEO and newly minted cool guy Mark Zuckerberg. Zuck's hour-long presentation will be followed by a developer-focused address at 11 am led by Meta CTO and Reality Labs chief Andrew Bosworth. You can watch the events on the Meta Connect website or on Meta's YouTube channel. And yes, you can also watch it in VR in Meta Horizon.</p><p>The focus of the event will likely be a fusion of Meta's mixed-reality efforts and its AI ambitions across its product line. Like any tech event, there are bound to be surprises. Here are the big things to look out for.</p>",
    readCount: 294,
    commentCount: 3,
    path: "4-meta-connect-starts-wednesday-here-s-what-to-expect",
  },
  {
    id: 5,
    tag: "Biz",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/microsoft.jpg",
    imgCaption: "Usual suspect of many viruses",
    imgCredit: "Microsoft",
    writer: "Rip Van Winkle",
    writerImg: "/img/user.jpg",
    title: "Do You Need an Antivirus Program on Windows?",
    content:
      "<p>Once upon a time, an antivirus program would be the one of the first pieces of software you would install on a new Windows PC. Now, that's much less common. Many users instead now rely on the Windows Security tool that's built into Microsoft's operating system to keep them protected against viruses and malware.</p><p>And yet, there are still plenty of antivirus and anti-malware security solutions for Windows. So should you be installing one of these packages? The answer, as you might expect, is that it depends.</p><p>We won't take you through the entire history of Microsoft Windows and its security features, but it's helpful to go back to September 2009: This was when a new program called Microsoft Security Essentials got added to the operating system. In the years since, that program has evolved and changed to become the Windows Security application you'll find preinstalled on your system today.</p>",
    readCount: 567,
    commentCount: 3,
    path: "5-do-you-need-an-antivirus-program-on-windows",
  },
  {
    id: 6,
    tag: "Biz",
    datetime: "2024/09/14 17:27",
    imgUrl: "/img/threads.jpg",
    imgCaption: "Threads: Cloning twitter toxicity",
    imgCredit: "Unsplash",
    writer: "Javier Escuella",
    writerImg: "/img/user.jpg",
    title: "Why Threads Is All the Rage Bait",
    content:
      "<p>One surefire way to go viral on Threads—the Meta-owned Instagram-spinoff social network with more than 200 million users—is to ask a ridiculous question that enrages your followers so much, they just have to chime in to answer you, mock you, or berate you. When it first launched last summer, Threads was seen as a blatant Twitter clone. At the time, that was an appealing attribute, as users fleeing the chaos and toxicity of the platform now known as X were looking for a new place to gather. Threads turned out to be a safe haven from the trolling and engagement bait on X, Reddit, and Facebook, but only for a while. Threads, like any for-profit social media site, was not able to keep those jokers and bad actors at bay. In its effort to boost engagement on the platform, Threads began prioritizing posts with the most replies and comments—which also happen to be the posts that stirred up the most drama and pissed everyone off</p><p>This week on Gadget Lab, we chat with Business Insider senior correspondent Katie Notopoulos about her personal experiment with rage-bait immersion on Threads. We also ask whether social media sites are making the right decision by catering to their most furious users.</p><p>If you're on an iPhone or iPad, open the app called Podcasts, or just tap this link. You can also download an app like Overcast or Pocket Casts, and search for Gadget Lab. If you use Android, you can find us in the Google Podcasts app just by tapping here. We're on Spotify too. And in case you really need it, here's the RSS feed.</p>",
    readCount: 883,
    commentCount: 3,
    path: "6-why-threads-is-all-the-rage-bait",
  },
  {
    id: 7,
    tag: "Biz",
    datetime: "2024/09/12 16:21",
    imgUrl: "/img/vinyl.jpg",
    imgCaption: "New breed of music industry",
    imgCredit: "Spotify",
    writer: "Sean Watson",
    writerImg: "/img/user.jpg",
    title: "The Music Industry's '90s Hard Drives Are Dying",
    content:
      "<p>One of the things enterprise storage and destruction company Iron Mountain does is handle the archiving of the media industry's vaults. What it has been seeing lately should be a wake-up call: Roughly one-fifth of the hard disk drives dating to the 1990s it was sent are entirely unreadable.</p><p>Music industry publication Mix spoke with the people in charge of backing up the entertainment industry. The resulting tale is part explainer on how music is so complicated to archive now, part warning about everyone's data stored on spinning disks.</p><p>'In our line of work, if we discover an inherent problem with a format, it makes sense to let everybody know,' Robert Koszela, global director for studio growth and strategic initiatives at Iron Mountain, told Mix. 'It may sound like a sales pitch, but it's not; it's a call for action.'</p>",
    readCount: 922,
    commentCount: 3,
    path: "7-the-music-industry-s-90s-hard-drives-are-dying",
  },
  {
    id: 8,
    tag: "Biz",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/wifi.jpg",
    imgCaption: "Be first to know what Wifi 7 is",
    imgCredit: "Getty Images",
    writer: "Dimaz Dije",
    writerImg: "/img/user.jpg",
    title: "What Is Wi-Fi 7? Here's Everything You Need to Know",
    content:
      "<p>While many people only recently upgraded to Wi-Fi 6 or Wi-Fi 6E, the successor to those standards has already arrived. Wi-Fi 7 is the next significant advance, and just like its predecessors, it promises faster connections, lower latency, and the ability to gracefully manage more connections.</p><p>If you are looking to improve your Wi-Fi today, Wi-Fi 7 could be the answer. The first wave of Wi-Fi 7 routers was very expensive, but we are starting to see more affordable options, and Wi-Fi 7 is supported by the latest devices, such as Apple's iPhone 16 range. If you need to upgrade pronto, first consider delving into how to buy a router before you check out our picks of the best Wi-Fi routers and the best mesh Wi-Fi systems.</p><p>The seventh generation of Wi-Fi brings major improvements over Wi-Fi 6 and 6E and can offer speeds up to four times faster. It also includes clever advances to reduce latency, increase capacity, and boost stability and efficiency.</p>",
    readCount: 649,
    commentCount: 3,
    path: "8-what-is-wi-fi-7-here-s-everything-you-need-to-know",
  },
  {
    id: 9,
    tag: "Biz",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/dumbphone.jpg",
    imgCaption: "Turn your gadget into early 2000's",
    imgCredit: "Unsplash",
    writer: "Kate Spade",
    writerImg: "/img/user.jpg",
    title: "How to Turn Your Smartphone Into a Dumb Phone",
    content:
      "<p>When the smartphone era began with the launch of the first iPhone in 2007 and the App Store a year later, part of the thrill of these devices was the sheer number of things they could do. Nearly two decades on, having a constantly distracting gadget that can do everything doesn't seem like quite such a good idea.</p><p>Some people have been turning back to feature phones to escape social media, instant messaging, and an endless barrage of content (now produced by AI as well as human beings). There are even dedicated phones built to stick to the basics, keeping useful features like driving directions and photo-taking, while ditching a lot of the noise and distraction that usually comes with a smartphone. But there's no need to buy a new device to achieve dumb-phone zen; by installing some apps and tweaking some of your phone's settings, you can slow the data deluge and reclaim some brain cycles.</p><p>If you're ready for a quieter life and keen to dumb down your smartphone, here's how to go about it on an iPhone or an Android device. These options are more comprehensive than simply uninstalling all your apps and turning off all your notifications, though you can certainly consider taking those steps too.</p>",
    readCount: 771,
    commentCount: 3,
    path: "9-how-to-turn-your-smartphone-into-a-dumb-phone",
  },
  {
    id: 10,
    tag: "Biz",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/ps5.jpg",
    imgCaption: "Play Uncharted in 7k",
    imgCredit: "Sony Entertainment",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title: "Sony's $700 PlayStation 5 Pro Is Finally Coming in November",
    content:
      "<p>Sony's PlayStation 5 mid-cycle upgrade, the PS5 Pro, is coming November 7. Lead PlayStation architect Mark Cerny revealed the console today during a brief video presentation. “Simply put, it's the most powerful console we've ever built,” Cerny said of the $700 device.</p><p>It's been four years since the PlayStation 5's launch. Although Sony released slimmer versions of the console last year, the PS5 Pro is its first major update to this generation's hardware. It's got a slightly changed look that features three ridged black stripes. More importantly, it's done away with predecessors' optical drive—a choice that's sure to be controversial among users.</p><p>Still, the PS5 Pro does add more power to players' gaming experiences. The new console includes an upgraded GPU that will allow for 45 percent faster gameplay rendering, as well as advanced ray tracing capabilities for better light rendering. Cerny's video presentation today included gameplay from Ratchet & Clank: Rift Apart, Control, The Last of Us Part 2, as well as many others, showing how games will run with higher fidelity on the new console.</p>",
    readCount: 864,
    commentCount: 3,
    path: "10-sony-s-$700-playstation-5-pro-is-finally-coming-in-november",
  },
  {
    id: 11,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/linux.jpg",
    imgCaption: "King of server world",
    imgCredit: "Linus Torvalds",
    writer: "Putri Amanda",
    writerImg: "/img/user.jpg",
    title:
      "Real-time Linux is officially part of the kernel after decades of debate",
    content:
      "<p>If you wanted to use 'Real-Time Linux' for your audio gear, your industrial welding laser, or your Mars rover, you have had that option for a long time (presuming you didn't want to use QNX or other alternatives). Universities started making their own real-time kernels in the late 1990s. A patch set, PREEMPT_RT, has existed since at least 2005. And some aspects of the real-time work, like NO_HZ, were long ago moved into the mainline kernel, enabling its use in data centers, cloud computing, or anything with a lot of CPUs.</p><p>But officialness still matters, and in the 6.12 kernel, PREEMPT_RT will likely be merged into the mainline. As noted by Steven Vaughan-Nichols at ZDNet, the final sign-off by Linus Torvalds occurred while he was attending Open Source Summit Europe. Torvalds wrote the original code for printk, a debugging tool that can pinpoint exact moments where a process crashes, but also introduces latency that runs counter to real-time computing. The Phoronix blog has tracked the progress of PREEMPT_RT into the kernel, along with the printk changes that allowed for threaded/atomic console support crucial to real-time mainlining.</p><p>What does this mean for desktop Linux? Not much. Beyond high-end audio production or replication (and even that is debatable), a real-time kernel won't likely make windows snappier or programs zippier. But the guaranteed execution and worst-case latency timings a real-time Linux provides are quite useful to, say, the systems that monitor car brakes, guide CNC machines, and regulate fiendishly complex multi-CPU systems. Having PREEMPT-RT in the mainline kernel makes it easier to maintain a real-time system, rather than tend to out-of-tree patches.</p>",
    readCount: 659,
    commentCount: 3,
    path: "11-real-time-linux-is-officially-part-of-the-kernel-after-decades-of-debate",
  },
  {
    id: 12,
    tag: "Tech",
    datetime: "2024/09/18 03:11",
    imgUrl: "/img/code.jpg",
    imgCaption: "Largest open source in the world",
    imgCredit: "Pexels",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title:
      "Neofetch is over, but many screenshot system info tools stand ready",
    content:
      "<p>Neofetch, run from a terminal, displayed key system information alongside an ASCII-art image of the operating system or distribution running on that system. You knew most of this data, but if you're taking a screenshot of your system, it looked cool and conveyed a lot of data in a small space. 'The overall purpose of Neofetch is to be used in screen-shots of your system,' wrote Neofetch's creator, Dylan Araps, on its Github repository. 'Neofetch shows the information other people want to see.'</p><p>Neofetch did that, providing cool screenshots and proof-of-life images across nearly 150 OS versions until late April. The last update to the tool was made three years before that, and Araps' Github profile now contains a rather succinct coda: 'Have taken up farming.' Araps joins 'going to a commune in Vermont' and 'I now make furniture out of wood' in the pantheon of programmers who do not just leave the field, but flee into another realm entirely.</p><p>Fastfetch seems to have captured the default forum/thread/blog recommendation as a Neofetch replacement. It is under active development, with changes occurring just hours before this post was published. It's highly customizable, available across most major platforms and distributions, and extensible through modules. It supports Wayland, provides more detailed memory and storage statistics, and, as the name suggests, is generally faster. It's FOSS and has a tutorial on customizing and extending Fastfetch.</p>",
    readCount: 338,
    commentCount: 3,
    path: "12-neofetch-is-over-but-many-screenshot-system-info-tools-stand-ready",
  },
  {
    id: 13,
    tag: "Tech",
    datetime: "2024/09/22 19:15",
    imgUrl: "/img/android.jpg",
    imgCaption: "New forced play by Google",
    imgCredit: "Google Inc",
    writer: "Hosea Matthews",
    writerImg: "/img/user.jpg",
    title:
      "Android apps are blocking sideloading and forcing Google Play versions instead",
    content:
      "<p>You might sideload an Android app, or manually install its APK package, if you're using a custom version of Android that doesn't include Google's Play Store. Alternately, the app might be experimental, under development, or perhaps no longer maintained and offered by its developer. Until now, the existence of sideload-ready APKs on the web was something that seemed to be tolerated, if warned against, by Google.</p><p>This quiet standstill is being shaken up by a new feature in Google's Play Integrity API. As reported by Android Authority, developer tools to push 'remediation' dialogs during sideloading debuted at Google's I/O conference in May, have begun showing up on users' phones. Sideloaders of apps from the British shop Tesco, fandom app BeyBlade X, and ChatGPT have reported 'Get this app from Play' prompts, which cannot be worked around. An Android gaming handheld user encountered a similarly worded prompt from Diablo Immortal on their device three months ago.</p><p>Google's Play Integrity API is how apps have previously blocked access when loaded onto phones that are in some way modified from a stock OS with all Google Play integrations intact. Recently, a popular two-factor authentication app blocked access on phones with modified firmware, including GrapheneOS, which aims to surpass the security of Android's stock system. Apps can call the Play Integrity API and get back an 'integrity verdict,' relaying if the phone has a 'trustworthy' software environment, has Google Play Protect enabled, and passes other software checks.",
    readCount: 448,
    commentCount: 3,
    path: "13-android-apps-are-blocking-sideloading-and-forcing-google-play-versions-instead",
  },
  {
    id: 14,
    tag: "Tech",
    datetime: "2024/09/23 15:51",
    imgUrl: "/img/dumbphone.jpg",
    imgCaption: "Sudden loss of subscription",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title:
      "FTC urged to make smart devices say how long they will be supported",
    content:
      "<p>For some of us, few things are more infuriating than a gadget that stops working due to a software change. As we've frequently covered here at Ars, startups and Big Tech companies are guilty of rendering hardware obsolete and/or stripping it of core functions. Consumer groups are urging the Federal Trade Commission to get involved.</p><p>In a letter sent today to Samuel Levine, director of the FTC's Bureau of Consumer Protection, and Serena Viswanathan, associate director of the FTC's Division of Advertising Practices, representatives from 17 groups, including Consumer Reports, the US PIRG, and iFixit, urged the FTC for 'clear guidance' around software tethering. Software tethering, per the letter, is 'making functions of a device reliant on embedded software that ties the device back to a manufacturer's servers.” As it stands, the practice is hurting customers with 'unfair and deceptive practices,' such as suddenly locking features behind a subscription—like the Snoo smart bassinet recently did—or bricking already-purchased devices, which Spotify did with its Car Thing.</p><p>The letter to the FTC argues that such practices hinder owners' ability to own their hardware.</p><p>'While the FTC has taken some limited actions with regard to this issue, a lack of clarity and enforcement has led to an ecosystem where consumers cannot reliably count on the connected products they buy to last,' the letter reads.</p>",
    readCount: 448,
    commentCount: 3,
    path: "14-ftc-urged-to-make-smart-devices-say-how-long-they-will-be-supported",
  },
  {
    id: 15,
    tag: "Tech",
    datetime: "2024/09/22 17:02",
    imgUrl: "/img/code.jpg",
    imgCaption: "Gen Z strikes Boomer coder",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title:
      "Rust in Linux lead retires rather than deal with more “nontechnical nonsense”",
    content:
      "<p>The Linux kernel is not a place to work if you're not ready for some, shall we say, spirited argument. Still, one key developer in the project to expand Rust's place inside the largely C-based kernel feels the 'nontechnical nonsense' is too much, so he's retiring.</p><p>Wedson Almeida Filho, a leader in the Rust for Linux project, wrote to the Linux kernel mailing list last week to remove himself as the project's maintainer. 'After almost 4 years, I find myself lacking the energy and enthusiasm I once had to respond to some of the nontechnical nonsense, so it's best to leave it up to those who still have it in them,' Filho wrote. While thanking his teammates, he noted that he believed the future of kernels 'is with memory-safe languages,' such as Rust. 'I am no visionary but if Linux doesn't internalize this, I'm afraid some other kernel will do to it what it did to Unix,' Filho wrote.</p><p>Filho also left a 'sample for context,' a link to a moment during a Linux conference talk in which an off-camera voice, identified by Filho in a Register interview as kernel maintainer Ted Ts'o, emphatically interjects: 'Here's the thing: you're not going to force all of us to learn Rust.' In the context of Filho's request that Linux's file system implement Rust bindings, Ts'o says that while he knows he must fix all the C code for any change he makes, he cannot or will not fix the Rust bindings that may be affected.</p>",
    readCount: 755,
    commentCount: 3,
    path: "15-rust-in-linux-lead-retires-rather-than-deal-with-more-nontechnical-nonsense",
  },
  {
    id: 16,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/app.jpg",
    imgCaption: "End of an era",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title: "Tumblr migrates more than 500 million blogs to WordPress",
    content:
      "<p>Once-great social media and blogging platform Tumblr has gone through a number of big changes in recent years, and another one is right around the corner. Parent company Automattic says it is migrating all Tumblr blogs—more than half a billion in number—to the WordPress back end.</p><p>In a blog post announcing the initiative this week, Automattic is careful to note that it doesn't want anything about the front-end user experience of Tumblr to change. 'We love Tumblr's streamlined posting experience and its current product direction. We're not changing that,' a rep wrote.</p><p>In terms of user experience, the two blogging platforms have very different emphases. WordPress is meant to be powerful, customizable, and extensible to serve a variety of needs, while Tumblr is meant to streamline the experience to be something like a middle ground between operating a WordPress blog and using something like X or Threads.</p>",
    readCount: 1200,
    commentCount: 3,
    path: "16-tumblr-migrates-more-than-500-million-blogs-to-wordpress",
  },
  {
    id: 17,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/pi5.jpg",
    imgCaption: "Joys of mini computing",
    imgCredit: "LTT Media",
    writer: "Linus Tech Tips",
    writerImg: "/img/user.jpg",
    title: "Revised Raspberry Pi 5 chip comes with unexpected power savings",
    content:
      "<p>When Raspberry Pi introduced a new 2GB version of the Raspberry Pi 5 board earlier this month, CEO Eben Upton said that the board would come with a slightly updated version of the board's Broadcom BCM2712C1 SoC. By removing chip functionality that the Pi 5 didn't use, the new D0 stepping of the chip would use less silicon, reducing its cost.</p><p>Raspberry Pi enthusiast and YouTuber Jeff Geerling has performed some firsthand testing of the 2GB Pi 5. As Upton said, the new board is functionally identical to the older 4GB and 8GB boards, with identical performance (as long as whatever workload you're running doesn't benefit from extra RAM, anyway). The new silicon die is also about 33 percent smaller than the old one, which Geerling verified by removing the SoC's heat spreader to expose the silicon underneath and measuring by hand.</p><p>Geerling also demonstrated that the 2GB Pi 5 comes with a couple of unexpected benefits that Upton didn't mention in his announcement—that the 2GB Pi 5 runs a little cooler and uses a little less power than the 4GB and 8GB editions. The 2GB Pi used just 2.4 W of power at idle and 8.9 W during a CPU stress test, compared to 3.3 W and 9.8 W in the 4GB version. The SoC of the 2GB Pi measured 30° Celsius at idle and 59° under load, compared to 32° and 63° for the 4GB version. Those are all small but significant differences, given that nothing has changed other than the SoC.</p>",
    readCount: 974,
    commentCount: 3,
    path: "17-revised-raspberry-pi-5-chip-comes-with-unexpected-power-savings",
  },
  {
    id: 18,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/unemployed.jpg",
    imgCaption: "AI really take over human jobs",
    imgCredit: "Apple Inc",
    writer: "Hussein Abri",
    writerImg: "/img/user.jpg",
    title: "Apple lays off employees working on Books and News",
    content:
      "<p>Apple will cut 100 jobs, all in its digital services teams. Laid off employees will have 60 days to find another job in the company before it cuts ties with them altogether, according to a Bloomberg report.</p><p>Compared to some other big tech companies, layoffs are relatively uncommon at Apple. This is the fourth wave this year, but cuts so far (including this one) have been laser-focused and small in scope—a contrast with companies like Intel, Cisco, or Microsoft, which have recently made more drastic cuts of anywhere from 7 to 15 percent of their workforces.</p><p>The current set of cuts chiefly affects the Books team. Digital services like this have been a big part of Apple's financial success in recent quarters; in just the past year, services revenue is up 14 percent. However, Books has no subscription offering, and Apple was subject to a US Department of Justice price-fixing lawsuit.</p>",
    readCount: 994,
    commentCount: 3,
    path: "18-apple-lays-off-employees-working-on-books-and-news",
  },
  {
    id: 19,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/chip.jpg",
    imgCaption: "Long live Duopoly!",
    imgCredit: "Advanced Micro Devices",
    writer: "John Marston",
    writerImg: "/img/user.jpg",
    title:
      "AMD signs $4.9 billion deal to challenge Nvidia's AI infrastructure lead",
    content:
      "<p>AMD has agreed to buy artificial intelligence infrastructure group ZT Systems in a $4.9 billion cash and stock transaction, extending a run of AI investments by the chip company as it seeks to challenge market-leader Nvidia.</p><p>The California-based group said the acquisition would help accelerate the adoption of its Instinct line of AI data center chips, which compete with Nvidia's popular graphics processing units (GPUs).</p><p>ZT Systems, a private company founded three decades ago, builds custom computing infrastructure for the biggest AI “hyperscalers.” While the company does not disclose its customers, the hyperscalers include the likes of Microsoft, Meta, and Amazon.</p><p>The deal marks AMD's biggest acquisition since it bought Xilinx for $35 billion in 2022.</p>",
    readCount: 837,
    commentCount: 3,
    path: "19-amd-signs-$49-billion-deal-to-challenge-nvidia-s-ai-infrastructure-lead",
  },
  {
    id: 20,
    tag: "Tech",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/reddit.jpg",
    imgCaption: "Real OG of forum websites",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/user.jpg",
    title: "Reddit considers search ads, paywalled content for the future",
    content:
      "<p>Reddit executives discussed plans on Tuesday for making more money from the platform, including showing ads in more places and possibly putting some content behind a paywall.</p><p>On Tuesday, Reddit shared its Q2 2024 earnings report (PDF). The company lost $10.1 million during the period, down from Q2 2023's $41.1 million loss. Reddit has never been profitable, and during its earnings call yesterday, company heads discussed potential and slated plans for monetization.</p><p>As expected, selling ads continues to be a priority. Part of the reason Reddit was OK with most third-party Reddit apps closing was that the change was expected to drive people to Reddit's native website and apps, where the company sells ads. In Q2, Reddit's ad revenue grew 41 percent year over year (YoY) to $253.1 million, or 90 percent of total revenue ($281.2 million).</p><p>When asked how the platform would grow ad revenue, Reddit COO Jen Wong said it's important that advertisers “find the outcomes they want at the volumes and price they want.” She also pointed to driving more value per ad, or the cost that advertisers pay per average 1,000 impressions. To do that, Wong pointed to putting ads in places on Reddit where there aren't ads currently:</p>",
    readCount: 448,
    commentCount: 3,
    path: "20-reddit-considers-search-ads-paywalled-content-for-the-future",
  },
  {
    id: 21,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/muskx.jpg",
    imgCaption: "Eccentric Billionaire strikes again",
    imgCredit: "Associated Press",
    writer: "Herr Strauss",
    writerImg: "/img/ryan.jpg",
    title:
      "Elon Musk's X gives up fight in Brazil, starts complying with judge's demands",
    content:
      "<p>Elon Musk is apparently conceding defeat in his fight with Brazil Supreme Court Judge Alexandre de Moraes, as the X social platform has started complying with the judge's demands in an attempt to get the service un-blocked in the country.</p><p>X previously refused to suspend dozens of accounts accused of spreading disinformation. Internet service providers have been blocking X under orders from the government since early September, and De Moraes seized $2 million from a Starlink bank account and $1.3 million from an X account to collect on fines issued to X.</p><p>X has claimed the orders violate Brazil's own laws. 'Unlike other social media and technology platforms, we will not comply in secret with illegal orders. To our users in Brazil and around the world, X remains committed to protecting your freedom of speech,' the company said in late August.</p><p>But in a reversal detailed in a court filing on Friday night, 'X's lawyers said the company had done exactly what Mr. Musk vowed not to: take down accounts that a Brazilian justice ordered removed because the judge said they threatened Brazil's democracy,' The New York Times reported. 'X also complied with the justice's other demands, including paying fines and naming a new formal representative in the country, the lawyers said.' (X said last month that its previous legal representative in Brazil resigned after de Moraes threatened her with imprisonment.)</p>",
    readCount: 943,
    commentCount: 3,
    path: "21-elon-musk-s-x-gives-up-fight-in-brazil-starts-complying-with-judge-s-demands",
  },
  {
    id: 22,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/google.jpg",
    imgCaption:
      "A DOJ win in Google's ad tech monopoly trial could benefit everyone, experts say.",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "How breaking up Google could lower your online shopping bill",
    content:
      "<p>As the US Department of Justice aims to break up Google's alleged ad tech monopoly, experts say that remedies sought in the antitrust trial could potentially benefit not just advertisers and publishers but also everyone targeted by ads online.</p><p>So far, the DOJ has argued that through acquisitions, Google allegedly monopolizes the ad server market, taking a substantial cut of every online ad sale by tying together products on the buyer and seller sides. Locking publishers into using its seller-side platform to access its large advertiser demand, Google also allegedly shut out rivals by pushing advertisers into a corner, then making it hard for publishers to switch platforms.</p><p>This scheme also allegedly set Google up to charge higher 'monopoly' fees, the DOJ argued, allegedly putting some publishers out of business and raising costs for advertisers.</p><p>But while the harms to publishers and advertisers have been outlined at length, there's been less talk about the seemingly major consequences for consumers perhaps harmed by the alleged monopoly. Those harms include higher costs of goods, less privacy, and increasingly lower-quality ads that frequently bombard their screens with products nobody wants.</p>",
    readCount: 799,
    commentCount: 3,
    path: "22-how-breaking-up-google-could-lower-your-online-shopping-bill",
  },
  {
    id: 23,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/unai.jpg",
    imgCaption:
      "UN report: Organization should take much more active role in AI monitoring, oversight.",
    imgCredit: "Associated Press",
    writer: "Ryan Dwiky",
    writerImg: "/img/ryan.jpg",
    title:
      "United Nations wants to treat AI with same urgency as climate change",
    content:
      "<p>A United Nations report released Thursday proposes having the international body oversee the first truly global effort for monitoring and governing artificial intelligence.</p><p>The report, produced by the UN secretary general's High Level Advisory Body on AI, recommends the creation of a body similar to the Intergovernmental Panel on Climate Change to gather up-to-date information on AI and its risks.</p><p>The report calls for a new policy dialog on AI so that the UN's 193 members can discuss risks and agree upon actions. It further recommends that the UN take steps to empower poorer nations, especially those in the global south, to benefit from AI and contribute to its governance. These should include, it says, creating an AI fund to back projects in these nations, establishing AI standards and data-sharing systems, and creating resources such as training to help nations with AI governance. Some of the report's recommendations could be facilitated by the Global Digital Compact, an existing plan to address digital and data divides between nations. It finally suggests creating an AI office within the UN dedicated to coordinating existing efforts within the UN to meet the report's goals.</p><p>“You've got an international community that agrees there are both harms and risks as well as opportunities presented by AI,” says Alondra Nelson, a professor at the Institute for Advanced Study who served on the UN advisory body at the recommendation of the White House and State Department.</p>",
    readCount: 1034,
    commentCount: 3,
    path: "23-united-nations-wants-to-treat-ai-with-same-urgency-as-climate-change",
  },
  {
    id: 24,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/linkedinai.jpg",
    imgCaption: "AI models may spout personal data",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "How to stop LinkedIn from training AI on your data",
    content:
      "<p>LinkedIn admitted Wednesday that it has been training its own AI on many users' data without seeking consent. Now there's no way for users to opt out of training that has already occurred, as LinkedIn limits opt-out to only future AI training.</p><p>In a blog detailing updates coming on November 20, LinkedIn general counsel Blake Lawit confirmed that LinkedIn's user agreement and privacy policy will be changed to better explain how users' personal data powers AI on the platform.</p><p>Under the new privacy policy, LinkedIn now informs users that 'we may use your personal data... [to] develop and train artificial intelligence (AI) models, develop, provide, and personalize our Services, and gain insights with the help of AI, automated systems, and inferences, so that our Services can be more relevant and useful to you and others.'</p><p>An FAQ explained that the personal data could be collected any time a user interacts with generative AI or other AI features, as well as when a user composes a post, changes their preferences, provides feedback to LinkedIn, or uses the platform for any amount of time.</p>",
    readCount: 1900,
    commentCount: 3,
    path: "24-how-to-stop-linkedin-from-training-ai-on-your-data",
  },
  {
    id: 25,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/amazon.jpg",
    imgCaption:
      "Amazon currently faces disgruntled workers in every direction.",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Backlash over Amazon's return to office comes as workers demand higher wages",
    content:
      "<p>Office workers are raging against CEO Andy Jassy's return to office mandate, Fortune reported—which came just as a leaked document reportedly showed that Amazon is also planning to gut management, Business Insider reported. Drivers by the hundreds are flocking to join a union to negotiate even better work conditions, CNBC reported, despite some of the biggest concessions in Amazon's history. And hundreds more unionized warehouse workers are increasingly banding together nationwide to demand a $25 an hour minimum wage. On Wednesday, workers everywhere were encouraged to leave Jassy a voicemail elevating workers' demands for a $25 minimum wage.</p><p>This momentum has been building for years after drivers unionized in 2021. And all this collective fury increasingly appears to be finally pressuring Amazon into negotiating better conditions for some workers.</p><p>Just last week, Amazon ponied up $2.1 billion—its 'biggest investment yet'—to improve driver safety and increase drivers' wages.</p><p>Unionizing warehouse workers told Ars that they're seeking a similar investment from Amazon, which currently pays on average a $20.50 minimum wage.</p>",
    readCount: 584,
    commentCount: 3,
    path: "25-backlash-over-amazon-s-return-to-office-comes-as-workers-demand-higher-wages",
  },
  {
    id: 26,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/zynga.jpg",
    imgCaption: "Hold'em. IBM!",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Zynga owes IBM $45M after using 1980s patented technology for hit games",
    content:
      "<p>Zynga must pay IBM nearly $45 million in damages after a jury ruled that popular games in its FarmVille series, as well as individual hits like Harry Potter: Puzzles and Spells, infringed on two early IBM patents.</p><p>In an SEC filing, Zynga reassured investors that 'the patents at issue have expired and Zynga will not have to modify or stop operating any of the games at issue' as a result of the loss. But the substantial damages owed will likely have financial implications for Zynga parent company Take-Two Interactive Software, analysts said, unless Zynga is successful in its plans to overturn the verdict.</p><p>A Take-Two spokesperson told Ars: 'We are disappointed in the verdict; however, believe we will prevail on appeal.'</p><p>For IBM, the win comes after a decade of failed attempts to stop what it claimed was Zynga's willful infringement of its patents.</p>",
    readCount: 520,
    commentCount: 3,
    path: "26-zynga-owes-ibm-45m-after-using-1980s-patented-technology-for-hit-games",
  },
  {
    id: 27,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/boeing.jpg",
    imgCaption: "Boeing deals with $45 billion debt.",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Boeing risks losing billions as 33,000 workers vote to strike",
    content:
      "<p>More than 33,000 unionized Boeing workers went on strike Friday, rejecting what they say were unfair terms of a deal the embattled aerospace company tentatively reached with their union.</p><p>The rejected deal tried and failed to win over workers by offering a 25 percent wage increase and promised to build Boeing's next jet in the Puget Sound region in Washington, which Boeing claimed offered 'job security for generations to come.'</p><p>But after International Association of Machinists and Aerospace Workers (IAM) District 751 president Jon Holden urged the union to accept the deal—which Boeing said was the 'largest-ever general wage increase' in the company's history—hundreds of Boeing employees immediately began resisting ahead of a Thursday vote that ultimately doomed the deal.</p><p>Instead of agreeing to a deal that compromised the desired 40 percent wage increases and eliminated workers' annual bonuses, about 96 percent of workers voted to strike, The Washington Post reported. Rather than take what Boeing offered, workers seized rare leverage amid Boeing's financial and production woes to pursue better terms.</p>",
    readCount: 648,
    commentCount: 3,
    path: "27-boeing-risks-losing-billions-as-33000-workers-vote-to-strike",
  },
  {
    id: 28,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/iphone.jpg",
    imgCaption: "€2.4 billion antitrust fine against Google",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Apple must pay €13 billion in back taxes after losing final appeal",
    content:
      "<p>Apple has suffered a significant defeat after the EU’s top court ruled that the iPhone maker must pay 13 billion euros in back taxes, overturning an earlier decision in the Big Tech group’s favor.</p><p>The ruling relates to a 2016 case when the EU’s competition chief Margrethe Vestager said that Ireland had given the company an illegal sweetheart deal, amounting to a tax rate of less than 1 percent.</p><p>The European Court of Justice said on Tuesday in its final ruling that it “confirms the European Commission’s 2016 decision: Ireland granted Apple unlawful aid which Ireland is required to recover.”</p><p>A lower court had in 2020 quashed the commission’s order and the ECJ’s decision to overturn that ruling was unexpectedly decisive.</p>",
    readCount: 920,
    commentCount: 3,
    path: "28-apple-must-pay-€13-billion-in-back-taxes-after-losing-final-appeal",
  },
  {
    id: 29,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/chaos.jpg",
    imgCaption: "Lack of proof of market harm",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Internet Archive’s e-book lending is not fair use, appeals court rules",
    content:
      "<p>The Internet Archive has lost its appeal after book publishers successfully sued to block the Open Libraries Project from lending digital scans of books for free online.</p><p>Judges for the Second Circuit Court of Appeals on Wednesday rejected the Internet Archive (IA) argument that its controlled digital lending—which allows only one person to borrow each scanned e-book at a time—was a transformative fair use that worked like a traditional library and did not violate copyright law.</p><p>As Judge Beth Robinson wrote in the decision, because the IA's digital copies of books did not 'provide criticism, commentary, or information about the originals' or alter the original books to add 'something new,' the court concluded that the IA's use of publishers' books was not transformative, hobbling the organization's fair use defense.</p><p>'IA’s digital books serve the same exact purpose as the originals: making authors’ works available to read,' Robinson said, emphasizing that in copyright law, however, '[n]ot every instance will be clear cut... this one is.'</p>",
    readCount: 378,
    commentCount: 3,
    path: "29-internet-archives-e-book-lending-is-not-fair-use-appeals-court-rules",
  },
  {
    id: 30,
    tag: "Policy",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/disney.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "TV viewers get screwed again as Disney channels are blacked out on DirecTV",
    content:
      "<p>Disney-owned channels have been blacked out on DirecTV for the past two days because of a contract dispute, with both companies claiming publicly that they aren't willing to budge much from their negotiating positions. Until it's resolved, DirecTV subscribers won't have access to ABC, ESPN, and other Disney channels.</p><p>While there have been many contentious contract negotiations between TV providers and programmers, this one is 'not a run-of-the-mill dispute,' DirecTV CFO Ray Carpenter said today in a call with reporters and analysts, according to The Hollywood Reporter. 'This is not the kind of dispute where we're haggling over percentage points on a rate. This is really about changing the model in a way that gives everyone confidence that this industry can survive.'</p><p>Carpenter was quoted as saying that DirecTV will fight Disney 'as long as it needs to' and accused Disney of timing the blackout before big sporting events 'to put the most pain and disruption on our customers.' Carpenter also said DirecTV doesn't 'have any dates drawn in the sand' and is 'not playing a short-term game,' according to Variety.</p><p>On Sunday, Disney issued a statement attributed to three executives at Disney Entertainment and ESPN. 'DirecTV chose to deny millions of subscribers access to our content just as we head into the final week of the US Open and gear up for college football and the opening of the NFL season,' the Disney statement said. 'While we're open to offering DirecTV flexibility and terms which we've extended to other distributors, we will not enter into an agreement that undervalues our portfolio of television channels and programs.'</p>",
    readCount: 800,
    commentCount: 3,
    path: "30-tv-viewers-get-screwed-again-as-disney-channels-are-blacked-out-on-directv",
  },
  {
    id: 31,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/ban.jpg",
    imgCaption: "start in model-year 2027",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "US to ban Chinese connected car software and hardware, citing security risks",
    content:
      "<p>The US government is readying its latest measure to defend local automotive manufacturing. In May, US President Joe Biden levied new 100 percent tariffs targeted at specific Chinese automakers. Now, the US Commerce Department is set to enact a de facto ban on most Chinese vehicles, by prohibiting Chinese connected car software and hardware from operating on US roads, according to Reuters.</p><p>The rationale? National security concerns. 'When foreign adversaries build software to make a vehicle [connected], that means it can be used for surveillance, can be remotely controlled, which threatens the privacy and safety of Americans on the road,' said Commerce Secretary Gina Raimondo.</p><p>'In an extreme situation, a foreign adversary could shut down or take control of all their vehicles operating in the United States all at the same time, causing crashes, blocking roads,' said Secretary Raimondo, a scenario we saw depicted in Fate of the Furious (where it caused me a headache), as well as more recently (and to better effect) in Leave the World Behind.</p><p>Hollywood aside, the idea that a connected car is a security risk is not something the US government has manufactured out of whole cloth. In fact, in 2021, China banned Tesla vehicles from its military bases and other state-controlled facilities after Chinese officials raised concerns about the rampant data collection abilities of the camera-studded Teslas.</p><p>Those fears were probably reasonable: it later emerged that for several years Tesla employees regularly shared with each other 'sometimes highly invasive videos and images,' captured by customer cars, over the company's messaging system.</p>",
    readCount: 1033,
    commentCount: 3,
    path: "31-us-to-ban-chinese-connected-car-software-and-hardware-citing-security-risks",
  },
  {
    id: 32,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/aidrive.jpg",
    imgCaption: "AI driver",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Driver assists become de facto autopilots as drivers multitask, study finds",
    content:
      "<p>The seductive lure of cars that drive themselves has led to an awful lot of hype over the past decade. Not everyone enjoys driving, after all, and the idea of freeing up the occupant to read their emails or watch a movie as their car grinds its way to their job led to billions in investments and a whole heck of a lot of GPU sales. We're still a long way from being able to buy a car with fully autonomous driving, but every OEM wants to sell you some level of partial automation that accelerates, brakes, and steers for you. There's just one problem—study after study shows these systems make us less safe on the road.</p><p>The latest data points come from a pair of studies just published by the Insurance Institute for Highway Safety (IIHS), one studying drivers using Tesla's Autopilot, the other focusing on Volvo's Pilot Assist. Both found that when drivers use partially automated driving systems, they pay less attention to the road and start multitasking instead.</p><p>The studies were conducted by IIHS together with the Center for Transportation and Logistics at MIT's AgeLab. The studies used Volvo S90 sedans and 2020 Tesla Model 3s, equipped with an array of cameras and sensors to monitor and record driver behavior.</p><p>In the Volvo study, of the 29 participants, none had ever driven an S90 before, and 22 had no familiarity using partially automated driving assists. All either commuted five days a week for at least 30 minutes on a highway (each way) or drove at least 100 miles (160 km) on a highway per week, commuting three to four times. The participants were split into three groups, with the third group given slightly different training on how to use the systems, then sent off to use the car as if it were their own for four weeks.</p>",
    readCount: 800,
    commentCount: 3,
    path: "32-driver-assists-become-de-facto-autopilots-as-drivers-multitask-study-finds",
  },
  {
    id: 33,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/waymo.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Human drivers keep rear-ending Waymos",
    content:
      "<p>On a Friday evening last November, police chased a silver sedan across the San Francisco Bay Bridge. The fleeing vehicle entered San Francisco and went careening through the city’s crowded streets. At the intersection of 11th and Folsom streets, it sideswiped the fronts of two other vehicles, veered onto a sidewalk, and hit two pedestrians.</p><p>According to a local news story, both pedestrians were taken to the hospital with one suffering major injuries. The driver of the silver sedan was injured, as was a passenger in one of the other vehicles.</p><p>No one was injured in the third car, a driverless Waymo robotaxi. Still, Waymo was required to report the crash to government agencies. It was one of 20 crashes with injuries that Waymo has reported through June.  And it’s the only crash Waymo has classified as causing a serious injury.</p><p>Twenty injuries might sound like a lot, but Waymo’s driverless cars have traveled more than 22 million miles. So driverless Waymo taxis have been involved in fewer than one injury-causing crash for every million miles of driving—a much better rate than a typical human driver.</p>",
    readCount: 995,
    commentCount: 3,
    path: "33-human-drivers-keep-rear-ending-waymos",
  },
  {
    id: 34,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/bmw.jpg",
    imgCaption: "BMW x Shell",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "BMW explains why it will sell hydrogen fuel cells in 2028",
    content:
      "<p>Today, BMW announced that it will start selling vehicles with hydrogen fuel cell powertrains in 2028 alongside the battery electric, gasoline-, and diesel-powered cars and SUVs it sells today. It is working with Toyota to develop new fuel cells, targeting half the cost and 20 percent better efficiency than current-generation fuel cell stacks. But the technology should be seen as complementary to battery electric vehicles, not a replacement for them, BMW said.</p><p>Earlier this morning, the automaker held a roundtable discussion with Michael Rath, BMW's vice president for hydrogen vehicles, who began by answering the main question I had been planning to ask well before any of the assembled journalists were called on.</p><p>'It's a fact: battery electric vehicles are more efficient in well-to-wheel than fuel cell electric vehicles. It's absolutely true that the conversion of electricity into hydrogen and back into electricity in the car generates losses and hence is less efficient than using the electricity directly,' Rath said.</p><p>BMW's position is that some regions have such high potential energy yields from solar or wind that it compensates for these conversion losses. That energy can be exported to renewable-poor regions—like Germany or Japan, for example—in the form of hydrogen. Along those lines, even in renewable-rich regions, hydrogen could be generated as a form of load balancing during times when it's sunny or especially windy, and there's a surplus.</p><p>'So if the electricity for the vehicle first has to be imported, as it is the case in many countries, then a solar panel in southern Spain or Australia will generate more energy in the same time and provide a similar driving range for an SUV, despite the energy intensive conversion processes involved,' Rath said.</p>",
    readCount: 834,
    commentCount: 3,
    path: "34-bmw-explains-why-it-will-sell-hydrogen-fuel-cells-in-2028",
  },
  {
    id: 35,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/aidrive.jpg",
    imgCaption: "Keep it essential",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "A lot of new in-car tech is “not necessary,” survey finds",
    content:
      "<p>Jumping into a new car from the driver's seat of something built before 2010 can cause quite the case of future shock. Over that time, automakers have been in a technology frenzy, loading up new vehicles with all manner of gizmos, gadgets, and features, some meant to make your life easier, others to make your journey safer. But do car buyers actually want all this stuff? A new survey by JD Power suggests they may not.</p><p>With enough time, a new convenience feature just becomes something buyers expect to be there. Starter motors replaced hand cranks for a reason, and I imagine most modern motorists would prefer not to deal with manual chokes. Manual window winders became more expensive and heavier than electric ones, leading to their extinction.</p><p>Some of the technology creep has come about by regulation or the threat of it. While many bemoan the 'iPad on the dash,' the legal requirement for a backup camera means there needs to be a screen in the car to display that feed. Steering wheels and dashboards grew to conceal airbags. And now vehicle fascias conceal sensors that can alert the driver or stop the car in the event of an imminent head-on crash.</p><p>But according to JD Power's Tech Experience Survey, which 'measures problems encountered and the user experience with advanced technologies as they first enter the market,' advanced technology in cars needs to solve real problems, and too much tech simply doesn't do that.</p>",
    readCount: 1189,
    commentCount: 3,
    path: "35-a-lot-of-new-in-car-tech-is-not-necessary-survey-finds",
  },
  {
    id: 36,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/boeing.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Lufthansa is using artificial sharkskin to streamline airplanes",
    content:
      "<p>Companies are often caught between wanting to cut emissions but also grow profits. But for airlines, these two different imperatives actually align. Cutting carbon emissions means burning less fuel and spending less money buying fuel. This is why Lufthansa has been copying a trick from the animal kingdom: applying a special film that mimics sharkskin to parts of its aircraft.</p><p>When it comes to decarbonization, reducing the emissions of air travel is both a high priority and something of a difficult task. Globally, air traffic accounts for about 2.5 percent of carbon emissions, but since those emissions are emitted at altitude, studies have found that the warming effect may be almost twice as large.</p><p>The problem is that it's extremely difficult to rival the volumetric energy density of jet fuel, which contains almost 50 times as many megajoules per liter than alternatives like hydrogen, ethanol, or lithium-ion batteries. That's less of a problem for ground or sea transportation, where weight and volume is less important, but it's a real stumbling block for switching jet airliners to a different fuel source.</p><p>Synthetic carbon fuels are obviously of great interest to the aviation sector, but they have their own problems—biofuels can divert cropland away from feeding humans, and the direct air capture of carbon dioxide to turn it into methane (and then more complex hydrocarbon fuels) is massively energy intensive and extremely expensive, costing perhaps five times as much as oil extracted from underground. And we're yet to see direct air capture working at a proper industrial scale, either.'</p>",
    readCount: 1165,
    commentCount: 3,
    path: "36-lufthansa-is-using-artificial-sharkskin-to-streamline-airplanes",
  },
  {
    id: 37,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/waymo.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Why the Fiat 500e could be your ideal second EV",
    content:
      "<p>Over two decades of parenting has left me with a healthy appreciation for SUVs and minivans. But there comes a time when the nest empties and transportation needs change. While it's useful to have a larger car around for road trips and hauling stuff around, one such vehicle is sufficient. The second car can be small, economical, energy efficient—the kind of car that I wouldn't have given a second glance in the past.</p><p>When Ars first drove the Fiat 500e last spring, we were impressed with what we saw and how it drove during the few hours spent behind the wheel. But Fiat is positioning this as an ideal second car, as Fiat CEO Olivier Francois told Ars at the drive. 'My ambition is not to replace your sedan or [S]UV.' The automaker wants the 500e to be your stylish but economical secondary ride.</p><p>After spending a week with the Fiat 500e Inspired by Beauty, I can attest that the 500e does indeed make for an ideal second car, at least if you don't have regular backseat passengers. Fiat's tiny hatchback is also one of the most efficient BEVs Ars has ever driven, as it consistently averaged 5 mi/kWh (12.4 kWh/100 km).</p><p>Returning to US shores after a five-year absence from the market, the 500e rolls on an all-new platform designed from the ground up for EVs. That's a great change—and here's a weird one. Instead of buying a black 500e, one purchases the Fiat 500e Inspired By Music edition, which is black. I drove the Fiat 500e Inspired By Beauty edition, which is a striking rose gold. The 500e is also available in red (RED) and silver Marine Layer Mist (Inspired By Los Angeles).</p>",
    readCount: 1067,
    commentCount: 3,
    path: "37-why-the-fiat-500e-could-be-your-ideal-second-ev",
  },
  {
    id: 38,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/kei.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "A cute, cheap death trap? Japanese Kei cars banned by yet another US state",
    content:
      "<p>Kei cars are the antithesis of the big American SUV. Where EPA regulations effectively penalize automakers for building smaller, more efficient cars, Japan's Kei car regulations cap size, weight, and power to just fractions. Kei cars aren't just small, they're also pretty cheap, a fact that has made them a sales success in Japan and highly desirable as a gray-market import, particularly by people who think new cars have gotten too large, too complicated, and too expensive. A few years ago, Ars even wrote a guide on how to go about importing one from Japan.</p><p>WBut not everyone is a fan of the diminutive Kei import. As far as the federal government is concerned, as long as it's more than 25 years old, an imported car does not have to comply with federal motor vehicle safety standards or fuel economy standards; just makes sure you pay all your import duties.</p><p>That's because the federal government doesn't license vehicles to operate on public roads. That task belongs to the individual states, and increasingly, they are giving Kei cars the thumbs down—sometimes even in cases where previously those cars posed no problem.</p><p>Some states restrict Kei cars—often Kei trucks, in this case—to working as farm vehicles; depending on the state, they may travel up to 20 miles from the farm. Some states like Alabama and Arkansas allow them with conditions such as speed restrictions or no highway use. And others are outright banning them. Georgia, Maine, and New York have all done so, and now Massachusetts is the latest to join that movement, helpfully even publishing a list of examples of Kei cars it won't now register.</p>",
    readCount: 993,
    commentCount: 3,
    path: "38-a-cute-cheap-death-trap-japanese-kei-cars-banned-by-yet-another-us-state",
  },
  {
    id: 39,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/disney.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Elon Musk says Tesla is an AI company now. Here’s how plausible that is.",
    content:
      "<p>When Tesla recorded its first annual profit in 2020, it had done something fairly remarkable. Starting a new car company has never been easy. It's harder still when those cars are electric and outside your average buyer's comfort zone; more than a dozen have tried and failed since Tesla was founded in 2003. Even mighty Apple, with all its billions in the bank, thought better of it. So why, after all that hard work, would Tesla's CEO now tell everyone that Tesla is an AI company?</p><p>The company's greatest successes have come when it innovates, like when it realized that laptop cells were about energy-dense enough to power a sports car if you just had enough of them. Building out a reliable fast-charging network was another such innovation. But Tesla CEO Elon Musk has also never been afraid to chase a trend, and the hype du jour is artificial intelligence, a field that attracted more than $67 billion in investment last year.</p><p>'We are an AI, robotics company; if you value us otherwise, the right answer is impossible to the questions being asked,' Musk told investors and journalists in April.</p><p>The company's profit and loss sheets back that up—Tesla was spending heavily on GPUs from Nvidia rather than on new car lines, although that was followed by news that Musk has had many of those GPUs redirected to his social media company X. And over the past few years, we've seen more demonstrations of humanoid robots—with varying degrees of verisimilitude—than new cars.</p><p>That lack of attention to the company's core business is starting to become evident. Tesla's product lineup is small and increasingly elderly, with the exception of a niche pickup truck that is only road-legal in North America. Price cuts haven't stopped sales from declining, and the company's profits are shrinking quarter by quarter.</p><p>In the corners of the Internet where people argue about such things, it's common to see appeals to the investors. Surely they can rein Musk in, get him to focus. Or maybe even replace him. That makes sense if the goal is to end up with a stable automaker that ticks along at a regular cadence. But those kinds of car companies just don't generate wild profit margins or solar system-sized valuations.</p>",
    readCount: 1125,
    commentCount: 3,
    path: "39-elon-musk-says-tesla-is-an-ai-company-now-heres-how-plausible-that-is",
  },
  {
    id: 40,
    tag: "Pop",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/disney.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "The 2025 Lucid Air is now the most efficient EV on sale",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1567,
    commentCount: 3,
    path: "40-the-2025-lucid-air-is-now-the-most-efficient-ev-on-sale",
  },
  {
    id: 41,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/ps5.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Nintendo, The Pokemon Company sue Palworld-maker Pocketpair",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1300,
    commentCount: 3,
    path: "41-nintendo-the-pokemon-company-sue-palworld-maker-pocketpair",
  },
  {
    id: 42,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/waymo.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Anti-cheat update leaves GTA Online’s Steam Deck players out in the cold",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 487,
    commentCount: 3,
    path: "42-anti-cheat-update-leaves-gta-onlines-steam-deck-players-out-in-the-cold",
  },
  {
    id: 43,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/workers.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "After 20 years, World of Warcraft will now let players do solo raids",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 921,
    commentCount: 3,
    path: "43-after-20-years-world-of-warcraft-will-now-let-players-do-solo-raids",
  },
  {
    id: 44,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/reddit.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "How crypto bros wrested Flappy Bird from its creator",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1035,
    commentCount: 3,
    path: "44-how-crypto-bros-wrested-flappy-bird-from-its-creator",
  },
  {
    id: 45,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/zynga.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Satisfactory is officially released, officially a scary wonderful time sink",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1054,
    commentCount: 3,
    path: "45-satisfactory-is-officially-released,-officially-a-scary-wonderful-time-sink",
  },
  {
    id: 46,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/unemployed.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "New AI model “learns” how to simulate Super Mario Bros. from video footage",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 847,
    commentCount: 3,
    path: "46-new-ai-model-learns-how-to-simulate-super-mario-bros.-from-video-footage",
  },
  {
    id: 47,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/linkedinai.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Valve’s worst-kept secret is no longer a secret",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 934,
    commentCount: 3,
    path: "47-valves-worst-kept-secret-is-no-longer-a-secret",
  },
  {
    id: 48,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/joker.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title:
      "Civilization VII hands-on: This strategy sequel rethinks the long game",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 985,
    commentCount: 3,
    path: "48-civilization-vii-hands-on-this-strategy-sequel-rethinks-the-long-game",
  },
  {
    id: 49,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/app.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "Behold, Diablo is fully playable in your browser",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1037,
    commentCount: 3,
    path: "49-behold-diablo-is-fully-playable-in-your-browser",
  },
  {
    id: 50,
    tag: "Culture",
    datetime: "2024/09/23 10:45",
    imgUrl: "/img/demonstration.jpg",
    imgCaption: "Two days into blackout",
    imgCredit: "Associated Press",
    writer: "Arthur Morgan",
    writerImg: "/img/ryan.jpg",
    title: "The new Riven remake is even better than Myst",
    content:
      "<p>Lucid has just revealed the details of its model-year 2025 updates, and among the tweaks to its handsome electric sedan is an impressive bump in range efficiency. The entry-level Lucid Air Pure, which starts at $69,900, can now travel 420 miles on a single charge of its 84 kWh battery. That equates to 5 miles/kWh (12.4 kWh/100 km), making the Air Pure the most efficient electric vehicle for sale today.</p><p>The range bump is mostly thanks to Lucid making a heat pump standard across the range, after first adding one to the ultra-powerful, ultra-expensive Air Sapphire.</p><p>Lucid has also upgraded the computer hardware that oversees the Air's various subsystems. The automaker says it has tripled processing power and doubled the system's memory, which should translate to faster and better infotainment. And Lucid has made its advanced driver assistance system standard across the lineup, too.</p><p>While the Air Pure might be the first production EV being sold to reach 5 miles/kWh, it isn't the longest-range Lucid Air for sale. That remains the $110,900 Grand Touring, which can go 512 miles (824 km) on a single charge. The 2025 Lucid Air Touring, which slots between them, has a range of 406 miles (654 km) and starts at $78,900.</p><p>While still a relative minnow compared to Rivian, Lucid has been on something of an upward trajectory of late. Price cuts have undoubtedly helped it have a record Q2, delivering 2,394 cars for its best three months so far.</p><p>Lucid's model-year 2025 data isn't in the EPA's online fuel economy database yet, so Ars can't check the slightly more detailed information there (which should break out the MPGe figure into city, highway, and combined figures), but 146 MPGe is only equivalent to 4.3 miles/kWh; 5 miles/kWh is 169 MPGe.</p>",
    readCount: 1043,
    commentCount: 3,
    path: "50-the-new-riven-remake-is-even-better-than-myst",
  },
];
