export const DUMMY_NEWS = [
    {
        id: 1,
        tag: "Biz",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/bomb.jpg",
        imgCaption: "World is shock to realize what Israel capable of",
        imgCredit: "Associated Press",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Your Phone Won't Be the Next Exploding Pager",
        content: "<p>For two days this week, Hezbollah has been rocked by a series of small explosions across Lebanon, injuring thousands and killing at least 25. But these attacks haven't come from rockets or drones. Instead, they've resulted from boobytrapped electronics—including pagers, walkie-talkies, and even, reportedly, solar equipment—detonating in coordinated waves. As details come into view of the elaborate supply chain attack that compromised these devices, citizens on the ground in Lebanon and people around the world are questioning whether such attacks could target any device in your pocket.</p><p>The campaign to compromise key Hezbollah communication infrastructure with explosives was clearly elaborate and involved. The operation, which is widely believed to have been perpetrated by Israel, goes far beyond past examples of hardware supply chain attacks and may be a source of inspiration for future spycraft around the world. But sources tell WIRED that the specific scale and scope of the effort would not be easily replicated in other contexts. And, more broadly, the resources and precision involved in carrying out such an attack would be prohibitively difficult to maintain over time for key consumer devices like smartphones—which are used so widely and regularly scrutinized by researchers, product testers, and repair technicians.</p><p>“I do think there is absolutely potential to see more of this in the longer term, not targeting civilians, but generally targeting other military actors,” says Zachary Kallenborn, an adjunct nonresident fellow with the Center for Strategic and International Studies. Kallenborn says militaries are increasingly relying on commercial technology—from drones to communications devices—all of which could be compromised if supply chains can be exploited by adversaries. “These systems are being sourced from all over the globe,” he says. “What that means, then, is that you also have these global supply chains supporting them.”</p>",
        readCount: 448,
        commentCount: 3,
    },
    {
        id: 2,
        tag: "Biz",
        datetime: "2024-09-16 08:52:08",
        imgUrl: "/img/movie.jpg",
        imgCaption: "Step up your smartphone game by creating movie",
        imgCredit: "Pexels",
        writer: "Micah Bell",
        writerImg: "/img/user.jpg",
        title: "28 Years Later: Danny Boyle's New Zombie Flick Was Shot on an iPhone 15",
        content: "<p>Even though professional, cinema-quality digital cameras are now commonplace, they're generally not small or compact. (Take a look at Arri's current lineup, for example, with its Mini LF, used to capture Deadpool & Wolverine.) However, Danny Boyle's forthcoming zombie flick, 28 Years Later, was shot over the summer with a bunch of adapted iPhone 15s, WIRED has learned, making the Hollywood thriller, with its budget of $75 million, the biggest movie to date filmed with smartphones.</p><p>Starring Killing Eve's Jodie Comer, next James Bond favorite Aaron Taylor-Johnson, and Ralph Fiennes, 28 Years Later, due for release in June 2025, is the long-awaited follow-up to 28 Days Later—the 2002 genre-defining movie that was the first to portray zombies as scary fast rather than lumbering—and 2007's 28 Weeks Later. Boyle is joined by cinematographer Anthony Dod Mantle; they won Oscars together in 2009 for their hit Slumdog Millionaire. Mantle was also cinematographer on the original 28 Days Later, as well as Boyle's films Trance (2013), T2 Trainspotting (2017), and 127 Hours (2010).</p><p>There's a tech story arc to Boyle and Mantle choosing Apples log-profile powerhouse for 28 Years Later: The pairs 2002 kick-off movie, 28 Days Later, was filmed with an innovative-for-the-time digital camera—one of the first Hollywood feature films shot with a Canon XL-1. The lust-worthy $4,000 prosumer camcorder had interchangeable lenses and wrote data to MiniDV (digital video) tapes.</p>",
        readCount: 753,
        commentCount: 3,
    },
    {
        id: 3,
        tag: "Biz",
        datetime: "2024-09-21 02:43:21",
        imgUrl: "/img/iphone.jpg",
        imgCaption: "Ios 18 join the GEN AI force",
        imgCredit: "Apple",
        writer: "Dutch Van der Linde",
        writerImg: "/img/user.jpg",
        title: "The Top New Features in Apple's iOS 18 and iPadOS 18",
        content: "<p>Apple executives always describe new hardware and software as the “best” or “biggest” ever, but the delivery doesn't usually live up to the hype (see the recent iPads). However, iOS 18 and iPadOS 18 might be deserving of a few of those adjectives. The new operating systems, which are now available, have the usual degree of year-over-year quality-of-life improvements, but Apple Intelligence stole the show.</p><p>Before installing the new operating system, I highly recommend you back up your devices. You can do this via iCloud—go to Settings, tap on your name at the top, and select iCloud. Then, tap on iCloud Backup, toggle it on, and tap Back Up Now to start a new backup. On the previous iCloud page, you also have the option to toggle off certain apps that you don't want to include in the backup. Don't have enough iCloud storage, or want to use another method? Check out our How to Back Up Your iPhone or iPad guide for alternative options.</p><p>Once you've backed up, you're ready to install iOS 18. Since this is a hefty update, you should plug your devices into a charger and ensure they're connected to Wi-Fi before the update starts. Now go to Settings > General > Software Update. You'll see the option to download the update. Tap Download and Install and, when the download is done, tap Install Now to start the update. You'll know the update is complete when your device restarts.</p>",
        readCount: 1067,
        commentCount: 3,
    },
    {
        id: 4,
        tag: "Biz",
        datetime: "2024-09-09 07:45:02",
        imgUrl: "/img/meta.jpg",
        imgCaption: "Biggest Meta conference incoming",
        imgCredit: "Facebook",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Meta Connect Starts Wednesday. Here's What to Expect",
        content: "<p>Meta Connect, the big developer event and hardware showcase from the company that runs Facebook and Instagram, is kicking off next week. Meta is likely to show off its new VR and mixed-reality technology, put a shiny polish on its meandering metaverse ambitions, and delve into all the fresh ways it plans to squeeze artificial intelligence into every crevice of its devices and services.</p><p>The event takes place on Wednesday September 25, starting at 10 am Pacific time. The keynote address, where most of the new stuff will be announced, will be livestreamed. The host for the event will be Meta CEO and newly minted cool guy Mark Zuckerberg. Zuck's hour-long presentation will be followed by a developer-focused address at 11 am led by Meta CTO and Reality Labs chief Andrew Bosworth. You can watch the events on the Meta Connect website or on Meta's YouTube channel. And yes, you can also watch it in VR in Meta Horizon.</p><p>The focus of the event will likely be a fusion of Meta's mixed-reality efforts and its AI ambitions across its product line. Like any tech event, there are bound to be surprises. Here are the big things to look out for.</p>",
        readCount: 294,
        commentCount: 3,
    },
    {
        id: 5,
        tag: "Biz",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/microsoft.jpg",
        imgCaption: "Usual suspect of many viruses",
        imgCredit: "Microsoft",
        writer: "Rip Van Winkle",
        writerImg: "/img/user.jpg",
        title: "Do You Need an Antivirus Program on Windows?",
        content: "<p>Once upon a time, an antivirus program would be the one of the first pieces of software you would install on a new Windows PC. Now, that's much less common. Many users instead now rely on the Windows Security tool that's built into Microsoft's operating system to keep them protected against viruses and malware.</p><p>And yet, there are still plenty of antivirus and anti-malware security solutions for Windows. So should you be installing one of these packages? The answer, as you might expect, is that it depends.</p><p>We won't take you through the entire history of Microsoft Windows and its security features, but it's helpful to go back to September 2009: This was when a new program called Microsoft Security Essentials got added to the operating system. In the years since, that program has evolved and changed to become the Windows Security application you'll find preinstalled on your system today.</p>",
        readCount: 567,
        commentCount: 3,
    },
    {
        id: 6,
        tag: "Biz",
        datetime: "2024-09-14 17:27:02",
        imgUrl: "/img/threads.jpg",
        imgCaption: "Threads: Cloning twitter toxicity",
        imgCredit: "Unsplash",
        writer: "Javier Escuella",
        writerImg: "/img/user.jpg",
        title: "Why Threads Is All the Rage Bait",
        content: "<p>One surefire way to go viral on Threads—the Meta-owned Instagram-spinoff social network with more than 200 million users—is to ask a ridiculous question that enrages your followers so much, they just have to chime in to answer you, mock you, or berate you. When it first launched last summer, Threads was seen as a blatant Twitter clone. At the time, that was an appealing attribute, as users fleeing the chaos and toxicity of the platform now known as X were looking for a new place to gather. Threads turned out to be a safe haven from the trolling and engagement bait on X, Reddit, and Facebook, but only for a while. Threads, like any for-profit social media site, was not able to keep those jokers and bad actors at bay. In its effort to boost engagement on the platform, Threads began prioritizing posts with the most replies and comments—which also happen to be the posts that stirred up the most drama and pissed everyone off</p><p>This week on Gadget Lab, we chat with Business Insider senior correspondent Katie Notopoulos about her personal experiment with rage-bait immersion on Threads. We also ask whether social media sites are making the right decision by catering to their most furious users.</p><p>If you're on an iPhone or iPad, open the app called Podcasts, or just tap this link. You can also download an app like Overcast or Pocket Casts, and search for Gadget Lab. If you use Android, you can find us in the Google Podcasts app just by tapping here. We're on Spotify too. And in case you really need it, here's the RSS feed.</p>",
        readCount: 883,
        commentCount: 3,
    },
    {
        id: 7,
        tag: "Biz",
        datetime: "2024-09-12 16:21:02",
        imgUrl: "/img/vinyl.jpg",
        imgCaption: "New breed of music industry",
        imgCredit: "Spotify",
        writer: "Sean Watson",
        writerImg: "/img/user.jpg",
        title: "The Music Industry's '90s Hard Drives Are Dying",
        content: "<p>One of the things enterprise storage and destruction company Iron Mountain does is handle the archiving of the media industry's vaults. What it has been seeing lately should be a wake-up call: Roughly one-fifth of the hard disk drives dating to the 1990s it was sent are entirely unreadable.</p><p>Music industry publication Mix spoke with the people in charge of backing up the entertainment industry. The resulting tale is part explainer on how music is so complicated to archive now, part warning about everyone's data stored on spinning disks.</p><p>'In our line of work, if we discover an inherent problem with a format, it makes sense to let everybody know,' Robert Koszela, global director for studio growth and strategic initiatives at Iron Mountain, told Mix. 'It may sound like a sales pitch, but it's not; it's a call for action.'</p>",
        readCount: 922,
        commentCount: 3,
    },
    {
        id: 8,
        tag: "Biz",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/wifi.jpg",
        imgCaption: "Be first to know what Wifi 7 is",
        imgCredit: "Getty Images",
        writer: "Dimaz Dije",
        writerImg: "/img/user.jpg",
        title: "What Is Wi-Fi 7? Here's Everything You Need to Know",
        content: "<p>While many people only recently upgraded to Wi-Fi 6 or Wi-Fi 6E, the successor to those standards has already arrived. Wi-Fi 7 is the next significant advance, and just like its predecessors, it promises faster connections, lower latency, and the ability to gracefully manage more connections.</p><p>If you are looking to improve your Wi-Fi today, Wi-Fi 7 could be the answer. The first wave of Wi-Fi 7 routers was very expensive, but we are starting to see more affordable options, and Wi-Fi 7 is supported by the latest devices, such as Apple's iPhone 16 range. If you need to upgrade pronto, first consider delving into how to buy a router before you check out our picks of the best Wi-Fi routers and the best mesh Wi-Fi systems.</p><p>The seventh generation of Wi-Fi brings major improvements over Wi-Fi 6 and 6E and can offer speeds up to four times faster. It also includes clever advances to reduce latency, increase capacity, and boost stability and efficiency.</p>",
        readCount: 649,
        commentCount: 3,
    },
    {
        id: 9,
        tag: "Biz",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/dumbphone.jpg",
        imgCaption: "Turn your gadget into early 2000's",
        imgCredit: "Unsplash",
        writer: "Kate Spade",
        writerImg: "/img/user.jpg",
        title: "How to Turn Your Smartphone Into a Dumb Phone",
        content: "<p>When the smartphone era began with the launch of the first iPhone in 2007 and the App Store a year later, part of the thrill of these devices was the sheer number of things they could do. Nearly two decades on, having a constantly distracting gadget that can do everything doesn't seem like quite such a good idea.</p><p>Some people have been turning back to feature phones to escape social media, instant messaging, and an endless barrage of content (now produced by AI as well as human beings). There are even dedicated phones built to stick to the basics, keeping useful features like driving directions and photo-taking, while ditching a lot of the noise and distraction that usually comes with a smartphone. But there's no need to buy a new device to achieve dumb-phone zen; by installing some apps and tweaking some of your phone's settings, you can slow the data deluge and reclaim some brain cycles.</p><p>If you're ready for a quieter life and keen to dumb down your smartphone, here's how to go about it on an iPhone or an Android device. These options are more comprehensive than simply uninstalling all your apps and turning off all your notifications, though you can certainly consider taking those steps too.</p>",
        readCount: 771,
        commentCount: 3,
    },
    {
        id: 10,
        tag: "Biz",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/ps5.jpg",
        imgCaption: "Play Uncharted in 7k",
        imgCredit: "Sony Entertainment",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Sony's $700 PlayStation 5 Pro Is Finally Coming in November",
        content: "<p>Sony's PlayStation 5 mid-cycle upgrade, the PS5 Pro, is coming November 7. Lead PlayStation architect Mark Cerny revealed the console today during a brief video presentation. “Simply put, it's the most powerful console we've ever built,” Cerny said of the $700 device.</p><p>It's been four years since the PlayStation 5's launch. Although Sony released slimmer versions of the console last year, the PS5 Pro is its first major update to this generation's hardware. It's got a slightly changed look that features three ridged black stripes. More importantly, it's done away with predecessors' optical drive—a choice that's sure to be controversial among users.</p><p>Still, the PS5 Pro does add more power to players' gaming experiences. The new console includes an upgraded GPU that will allow for 45 percent faster gameplay rendering, as well as advanced ray tracing capabilities for better light rendering. Cerny's video presentation today included gameplay from Ratchet & Clank: Rift Apart, Control, The Last of Us Part 2, as well as many others, showing how games will run with higher fidelity on the new console.</p>",
        readCount: 864,
        commentCount: 3,
    },
    {
        id: 11,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/linux.jpg",
        imgCaption: "King of server world",
        imgCredit: "Linus Torvalds",
        writer: "Putri Amanda",
        writerImg: "/img/user.jpg",
        title: "Real-time Linux is officially part of the kernel after decades of debate",
        content: "<p>If you wanted to use 'Real-Time Linux' for your audio gear, your industrial welding laser, or your Mars rover, you have had that option for a long time (presuming you didn't want to use QNX or other alternatives). Universities started making their own real-time kernels in the late 1990s. A patch set, PREEMPT_RT, has existed since at least 2005. And some aspects of the real-time work, like NO_HZ, were long ago moved into the mainline kernel, enabling its use in data centers, cloud computing, or anything with a lot of CPUs.</p><p>But officialness still matters, and in the 6.12 kernel, PREEMPT_RT will likely be merged into the mainline. As noted by Steven Vaughan-Nichols at ZDNet, the final sign-off by Linus Torvalds occurred while he was attending Open Source Summit Europe. Torvalds wrote the original code for printk, a debugging tool that can pinpoint exact moments where a process crashes, but also introduces latency that runs counter to real-time computing. The Phoronix blog has tracked the progress of PREEMPT_RT into the kernel, along with the printk changes that allowed for threaded/atomic console support crucial to real-time mainlining.</p><p>What does this mean for desktop Linux? Not much. Beyond high-end audio production or replication (and even that is debatable), a real-time kernel won't likely make windows snappier or programs zippier. But the guaranteed execution and worst-case latency timings a real-time Linux provides are quite useful to, say, the systems that monitor car brakes, guide CNC machines, and regulate fiendishly complex multi-CPU systems. Having PREEMPT-RT in the mainline kernel makes it easier to maintain a real-time system, rather than tend to out-of-tree patches.</p>",
        readCount: 659,
        commentCount: 3,
    },
    {
        id: 12,
        tag: "Tech",
        datetime: "2024-09-18 03:11:02",
        imgUrl: "/img/code.jpg",
        imgCaption: "Largest open source in the world",
        imgCredit: "Pexels",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Neofetch is over, but many screenshot system info tools stand ready",
        content: "<p>Neofetch, run from a terminal, displayed key system information alongside an ASCII-art image of the operating system or distribution running on that system. You knew most of this data, but if you're taking a screenshot of your system, it looked cool and conveyed a lot of data in a small space. 'The overall purpose of Neofetch is to be used in screen-shots of your system,' wrote Neofetch's creator, Dylan Araps, on its Github repository. 'Neofetch shows the information other people want to see.'</p><p>Neofetch did that, providing cool screenshots and proof-of-life images across nearly 150 OS versions until late April. The last update to the tool was made three years before that, and Araps' Github profile now contains a rather succinct coda: 'Have taken up farming.' Araps joins 'going to a commune in Vermont' and 'I now make furniture out of wood' in the pantheon of programmers who do not just leave the field, but flee into another realm entirely.</p><p>Fastfetch seems to have captured the default forum/thread/blog recommendation as a Neofetch replacement. It is under active development, with changes occurring just hours before this post was published. It's highly customizable, available across most major platforms and distributions, and extensible through modules. It supports Wayland, provides more detailed memory and storage statistics, and, as the name suggests, is generally faster. It's FOSS and has a tutorial on customizing and extending Fastfetch.</p>",
        readCount: 338,
        commentCount: 3,
    },
    {
        id: 13,
        tag: "Tech",
        datetime: "2024-09-22 19:15:47",
        imgUrl: "/img/android.jpg",
        imgCaption: "New forced play by Google",
        imgCredit: "Google Inc",
        writer: "Hosea Matthews",
        writerImg: "/img/user.jpg",
        title: "Android apps are blocking sideloading and forcing Google Play versions instead",
        content: "<p>You might sideload an Android app, or manually install its APK package, if you're using a custom version of Android that doesn't include Google's Play Store. Alternately, the app might be experimental, under development, or perhaps no longer maintained and offered by its developer. Until now, the existence of sideload-ready APKs on the web was something that seemed to be tolerated, if warned against, by Google.</p><p>This quiet standstill is being shaken up by a new feature in Google's Play Integrity API. As reported by Android Authority, developer tools to push 'remediation' dialogs during sideloading debuted at Google's I/O conference in May, have begun showing up on users' phones. Sideloaders of apps from the British shop Tesco, fandom app BeyBlade X, and ChatGPT have reported 'Get this app from Play' prompts, which cannot be worked around. An Android gaming handheld user encountered a similarly worded prompt from Diablo Immortal on their device three months ago.</p><p>Google's Play Integrity API is how apps have previously blocked access when loaded onto phones that are in some way modified from a stock OS with all Google Play integrations intact. Recently, a popular two-factor authentication app blocked access on phones with modified firmware, including GrapheneOS, which aims to surpass the security of Android's stock system. Apps can call the Play Integrity API and get back an 'integrity verdict,' relaying if the phone has a 'trustworthy' software environment, has Google Play Protect enabled, and passes other software checks.",
        readCount: 448,
        commentCount: 3,
    },
    {
        id: 14,
        tag: "Tech",
        datetime: "2024-09-23 15:51:02",
        imgUrl: "/img/dumbphone.jpg",
        imgCaption: "Sudden loss of subscription",
        imgCredit: "Associated Press",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "FTC urged to make smart devices say how long they will be supported",
        content: "<p>For some of us, few things are more infuriating than a gadget that stops working due to a software change. As we've frequently covered here at Ars, startups and Big Tech companies are guilty of rendering hardware obsolete and/or stripping it of core functions. Consumer groups are urging the Federal Trade Commission to get involved.</p><p>In a letter sent today to Samuel Levine, director of the FTC's Bureau of Consumer Protection, and Serena Viswanathan, associate director of the FTC's Division of Advertising Practices, representatives from 17 groups, including Consumer Reports, the US PIRG, and iFixit, urged the FTC for 'clear guidance' around software tethering. Software tethering, per the letter, is 'making functions of a device reliant on embedded software that ties the device back to a manufacturer's servers.” As it stands, the practice is hurting customers with 'unfair and deceptive practices,' such as suddenly locking features behind a subscription—like the Snoo smart bassinet recently did—or bricking already-purchased devices, which Spotify did with its Car Thing.</p><p>The letter to the FTC argues that such practices hinder owners' ability to own their hardware.</p><p>'While the FTC has taken some limited actions with regard to this issue, a lack of clarity and enforcement has led to an ecosystem where consumers cannot reliably count on the connected products they buy to last,' the letter reads.</p>",
        readCount: 448,
        commentCount: 3,
    },
    {
        id: 15,
        tag: "Tech",
        datetime: "2024-09-22 17:02:10",
        imgUrl: "/img/code.jpg",
        imgCaption: "Gen Z strikes Boomer coder",
        imgCredit: "Associated Press",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Rust in Linux lead retires rather than deal with more “nontechnical nonsense”",
        content: "<p>The Linux kernel is not a place to work if you're not ready for some, shall we say, spirited argument. Still, one key developer in the project to expand Rust's place inside the largely C-based kernel feels the 'nontechnical nonsense' is too much, so he's retiring.</p><p>Wedson Almeida Filho, a leader in the Rust for Linux project, wrote to the Linux kernel mailing list last week to remove himself as the project's maintainer. 'After almost 4 years, I find myself lacking the energy and enthusiasm I once had to respond to some of the nontechnical nonsense, so it's best to leave it up to those who still have it in them,' Filho wrote. While thanking his teammates, he noted that he believed the future of kernels 'is with memory-safe languages,' such as Rust. 'I am no visionary but if Linux doesn't internalize this, I'm afraid some other kernel will do to it what it did to Unix,' Filho wrote.</p><p>Filho also left a 'sample for context,' a link to a moment during a Linux conference talk in which an off-camera voice, identified by Filho in a Register interview as kernel maintainer Ted Ts'o, emphatically interjects: 'Here's the thing: you're not going to force all of us to learn Rust.' In the context of Filho's request that Linux's file system implement Rust bindings, Ts'o says that while he knows he must fix all the C code for any change he makes, he cannot or will not fix the Rust bindings that may be affected.</p>",
        readCount: 755,
        commentCount: 3,
    },
    {
        id: 16,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/app.jpg",
        imgCaption: "End of an era",
        imgCredit: "Associated Press",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Tumblr migrates more than 500 million blogs to WordPress",
        content: "<p>Once-great social media and blogging platform Tumblr has gone through a number of big changes in recent years, and another one is right around the corner. Parent company Automattic says it is migrating all Tumblr blogs—more than half a billion in number—to the WordPress back end.</p><p>In a blog post announcing the initiative this week, Automattic is careful to note that it doesn't want anything about the front-end user experience of Tumblr to change. 'We love Tumblr's streamlined posting experience and its current product direction. We're not changing that,' a rep wrote.</p><p>In terms of user experience, the two blogging platforms have very different emphases. WordPress is meant to be powerful, customizable, and extensible to serve a variety of needs, while Tumblr is meant to streamline the experience to be something like a middle ground between operating a WordPress blog and using something like X or Threads.</p>",
        readCount: 1200,
        commentCount: 3,
    },
    {
        id: 17,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/pi5.jpg",
        imgCaption: "Joys of mini computing",
        imgCredit: "LTT Media",
        writer: "Linus Tech Tips",
        writerImg: "/img/user.jpg",
        title: "Revised Raspberry Pi 5 chip comes with unexpected power savings",
        content: "<p>When Raspberry Pi introduced a new 2GB version of the Raspberry Pi 5 board earlier this month, CEO Eben Upton said that the board would come with a slightly updated version of the board's Broadcom BCM2712C1 SoC. By removing chip functionality that the Pi 5 didn't use, the new D0 stepping of the chip would use less silicon, reducing its cost.</p><p>Raspberry Pi enthusiast and YouTuber Jeff Geerling has performed some firsthand testing of the 2GB Pi 5. As Upton said, the new board is functionally identical to the older 4GB and 8GB boards, with identical performance (as long as whatever workload you're running doesn't benefit from extra RAM, anyway). The new silicon die is also about 33 percent smaller than the old one, which Geerling verified by removing the SoC's heat spreader to expose the silicon underneath and measuring by hand.</p><p>Geerling also demonstrated that the 2GB Pi 5 comes with a couple of unexpected benefits that Upton didn't mention in his announcement—that the 2GB Pi 5 runs a little cooler and uses a little less power than the 4GB and 8GB editions. The 2GB Pi used just 2.4 W of power at idle and 8.9 W during a CPU stress test, compared to 3.3 W and 9.8 W in the 4GB version. The SoC of the 2GB Pi measured 30° Celsius at idle and 59° under load, compared to 32° and 63° for the 4GB version. Those are all small but significant differences, given that nothing has changed other than the SoC.</p>",
        readCount: 974,
        commentCount: 3,
    },
    {
        id: 18,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/unemployed.jpg",
        imgCaption: "AI really take over human jobs",
        imgCredit: "Apple Inc",
        writer: "Hussein Abri",
        writerImg: "/img/user.jpg",
        title: "Apple lays off employees working on Books and News",
        content: "<p>Apple will cut 100 jobs, all in its digital services teams. Laid off employees will have 60 days to find another job in the company before it cuts ties with them altogether, according to a Bloomberg report.</p><p>Compared to some other big tech companies, layoffs are relatively uncommon at Apple. This is the fourth wave this year, but cuts so far (including this one) have been laser-focused and small in scope—a contrast with companies like Intel, Cisco, or Microsoft, which have recently made more drastic cuts of anywhere from 7 to 15 percent of their workforces.</p><p>The current set of cuts chiefly affects the Books team. Digital services like this have been a big part of Apple's financial success in recent quarters; in just the past year, services revenue is up 14 percent. However, Books has no subscription offering, and Apple was subject to a US Department of Justice price-fixing lawsuit.</p>",
        readCount: 994,
        commentCount: 3,
    },
    {
        id: 19,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/chip.jpg",
        imgCaption: "Long live Duopoly!",
        imgCredit: "Advanced Micro Devices",
        writer: "John Marston",
        writerImg: "/img/user.jpg",
        title: "AMD signs $4.9 billion deal to challenge Nvidia's AI infrastructure lead",
        content: "<p>AMD has agreed to buy artificial intelligence infrastructure group ZT Systems in a $4.9 billion cash and stock transaction, extending a run of AI investments by the chip company as it seeks to challenge market-leader Nvidia.</p><p>The California-based group said the acquisition would help accelerate the adoption of its Instinct line of AI data center chips, which compete with Nvidia's popular graphics processing units (GPUs).</p><p>ZT Systems, a private company founded three decades ago, builds custom computing infrastructure for the biggest AI “hyperscalers.” While the company does not disclose its customers, the hyperscalers include the likes of Microsoft, Meta, and Amazon.</p><p>The deal marks AMD's biggest acquisition since it bought Xilinx for $35 billion in 2022.</p>",
        readCount: 837,
        commentCount: 3,
    },
    {
        id: 20,
        tag: "Tech",
        datetime: "2024-09-23 10:45:02",
        imgUrl: "/img/reddit.jpg",
        imgCaption: "Real OG of forum websites",
        imgCredit: "Associated Press",
        writer: "Arthur Morgan",
        writerImg: "/img/user.jpg",
        title: "Reddit considers search ads, paywalled content for the future",
        content: "<p>Reddit executives discussed plans on Tuesday for making more money from the platform, including showing ads in more places and possibly putting some content behind a paywall.</p><p>On Tuesday, Reddit shared its Q2 2024 earnings report (PDF). The company lost $10.1 million during the period, down from Q2 2023's $41.1 million loss. Reddit has never been profitable, and during its earnings call yesterday, company heads discussed potential and slated plans for monetization.</p><p>As expected, selling ads continues to be a priority. Part of the reason Reddit was OK with most third-party Reddit apps closing was that the change was expected to drive people to Reddit's native website and apps, where the company sells ads. In Q2, Reddit's ad revenue grew 41 percent year over year (YoY) to $253.1 million, or 90 percent of total revenue ($281.2 million).</p><p>When asked how the platform would grow ad revenue, Reddit COO Jen Wong said it's important that advertisers “find the outcomes they want at the volumes and price they want.” She also pointed to driving more value per ad, or the cost that advertisers pay per average 1,000 impressions. To do that, Wong pointed to putting ads in places on Reddit where there aren't ads currently:</p>",
        readCount: 448,
        commentCount: 3,
    },
]