export const DUMMY_FORUMS = [
  {
    id: "1",
    title: "What are the best frameworks for React in 2026?",
    author: "DevMaster",
    date: "2026-04-25",
    commentsCount: 42,
    content: "With so many options out there, I'm curious what everyone is using for their professional projects these days. Is Next.js still the king?",
    hot: true,
    comments: [
      {
        id: "c1",
        author: "ReactFan",
        date: "2026-04-25",
        text: "Next.js is definitely still leading, but I've been seeing a lot of growth in Remix lately.",
      },
      {
        id: "c2",
        author: "ModernWeb",
        date: "2026-04-26",
        text: "I've moved back to Vite + a custom router for smaller projects. The simplicity is unmatched.",
      },
    ],
  },
  {
    id: "2",
    title: "How to optimize Next.js Image component for 8K displays?",
    author: "PixelPerfect",
    date: "2026-04-24",
    commentsCount: 15,
    content: "I'm working on a high-end portfolio site and need to serve massive images without killing performance. Any tips?",
    hot: true,
    comments: [{
      id: "c1",
      author: "StuckOverflow",
      date: "2026-04-25",
      text: "What a dumb questions!!",
    }],
  },
  {
    id: "3",
    title: "Cybersecurity trends to watch this year",
    author: "SecureGuy",
    date: "2026-04-26",
    commentsCount: 8,
    content: "AI-driven attacks are becoming more common. How are you protecting your cloud infrastructure?",
    hot: false,
    comments: [],
  },
  {
    id: "4",
    title: "Is Tailwind CSS still relevant or are we going back to Vanilla CSS?",
    author: "StyleLover",
    date: "2026-04-26",
    commentsCount: 120,
    content: "I've seen some discussions about utility-first CSS being hard to maintain in large teams. What's your take?",
    hot: false,
    comments: [],
  },
];
