export const DUMMY_FORUMS = [
  {
    id: "1",
    title: "What are the best frameworks for React in 2026?",
    author: "DevMaster",
    date: "2026-04-25",
    commentsCount: 42,
    content: "With so many options out there, I'm curious what everyone is using for their professional projects these days. Is Next.js still the king?",
    hot: true,
    comments: [
      {
        id: "c1",
        author: "ReactFan",
        date: "2026-04-25",
        text: "Next.js is definitely still leading, but I've been seeing a lot of growth in Remix lately.",
      },
      {
        id: "c2",
        author: "ModernWeb",
        date: "2026-04-26",
        text: "I've moved back to Vite + a custom router for smaller projects. The simplicity is unmatched.",
      },
    ],
  },
  {
    id: "2",
    title: "How to optimize Next.js Image component for 8K displays?",
    author: "PixelPerfect",
    date: "2026-04-24",
    commentsCount: 15,
    content: "I'm working on a high-end portfolio site and need to serve massive images without killing performance. Any tips?",
    hot: true,
    comments: [{
      id: "c1",
      author: "StuckOverflow",
      date: "2026-04-25",
      text: "What a dumb questions!!",
    }],
  },
  {
    id: "3",
    title: "Cybersecurity trends to watch this year",
    author: "SecureGuy",
    date: "2026-04-26",
    commentsCount: 8,
    content: "AI-driven attacks are becoming more common. How are you protecting your cloud infrastructure?",
    hot: false,
    comments: [],
  },
  {
    id: "4",
    title: "Is Tailwind CSS still relevant or are we going back to Vanilla CSS?",
    author: "StyleLover",
    date: "2026-04-26",
    commentsCount: 120,
    content: "I've seen some discussions about utility-first CSS being hard to maintain in large teams. What's your take?",
    hot: false,
    comments: [],
  },
  {
    id: "5",
    title: "Startup Funding Trends in Jakarta for Q2 2026",
    author: "VentureVibe",
    date: "2026-04-20",
    commentsCount: 28,
    content: "Are we seeing a shift towards sustainable profitability or is high growth still the main metric for Jakarta VCs?",
    hot: true,
    comments: [
      {
        id: "c1",
        author: "FounderDaily",
        date: "2026-04-21",
        text: "Profitability is definitely the new 'cool'. VCs are asking for unit economics on day one now.",
      },
    ],
  },
  {
    id: "6",
    title: "New Government Regulation on AI Ethics in Indonesia",
    author: "LegalTechID",
    date: "2026-04-22",
    commentsCount: 54,
    content: "The Ministry of Communication and Information just released a new draft. What does this mean for local AI startups?",
    hot: true,
    comments: [],
  },
  {
    id: "7",
    title: "Best Coworking Spaces in Bali with 1Gbps Connection",
    author: "DigitalNomad",
    date: "2026-04-18",
    commentsCount: 12,
    content: "Planning a workation in Canggu. Any recommendations for spots that actually have stable high-speed internet?",
    hot: false,
    comments: [
      {
        id: "c1",
        author: "SurfAndCode",
        date: "2026-04-19",
        text: "Check out the new hub in Pererenan, they have dedicated fiber lines now.",
      },
    ],
  },
  {
    id: "8",
    title: "Biznet vs Telkom Cloud: Which one for local scaling?",
    author: "SysAdminID",
    date: "2026-04-15",
    commentsCount: 33,
    content: "We want to keep our data within Indonesian borders. Which provider offers the best reliability for a high-traffic app?",
    hot: false,
    comments: [],
  },
  {
    id: "9",
    title: "GoTo's Expansion into the Web3 Space",
    author: "CryptoKoran",
    date: "2026-04-10",
    commentsCount: 89,
    content: "The rumors were true! GoTo is launching their own NFT marketplace integrated with GoPay.",
    hot: true,
    comments: [],
  },
  {
    id: "10",
    title: "Is Rust worth learning for Indonesian Backend Devs in 2026?",
    author: "FerrisFans",
    date: "2026-04-12",
    commentsCount: 45,
    content: "Seeing more job listings requiring Rust for systems programming. Is it time to switch from Go?",
    hot: false,
    comments: [
      {
        id: "c1",
        author: "GopherID",
        date: "2026-04-13",
        text: "Go is still king for microservices here, but Rust is great for specific performance bottlenecks.",
      },
    ],
  },
  {
    id: "11",
    title: "EV Charging Infrastructure Software Opportunities",
    author: "GreenTech",
    date: "2026-04-14",
    commentsCount: 22,
    content: "As EVs flood Jakarta's streets, the management software for charging stations is becoming a huge market.",
    hot: false,
    comments: [],
  },
  {
    id: "12",
    title: "Transitioning from Senior Dev to Product Manager in ID Startups",
    author: "CareerPath",
    date: "2026-04-16",
    commentsCount: 19,
    content: "Anyone successfully made the jump? What are the biggest cultural shifts in local tech companies?",
    hot: false,
    comments: [],
  },
  {
    id: "13",
    title: "Nusantara Smart City: The Tech Stack Behind the New Capital",
    author: "GovGeek",
    date: "2026-04-17",
    commentsCount: 110,
    content: "Diving deep into the IoT and digital twin technologies being used in the construction of Nusantara.",
    hot: true,
    comments: [],
  },
  {
    id: "14",
    title: "Mobile Gaming Trends: Why MOBA is still dominant in SE Asia",
    author: "GamerPro",
    date: "2026-04-21",
    commentsCount: 67,
    content: "Despite the rise of AR/VR, mobile MOBAs like MLBB continue to break concurrent player records.",
    hot: true,
    comments: [],
  },
  {
    id: "15",
    title: "React Native vs Flutter: The 2026 Verdict for SE Asian Markets",
    author: "AppWizard",
    date: "2026-04-23",
    commentsCount: 92,
    content: "With the latest performance updates, which cross-platform framework is winning the hearts of local agencies?",
    hot: false,
    comments: [],
  },
  {
    id: "16",
    title: "The Impact of 6G Pilot Tests in Jakarta Sudirman Area",
    author: "NetworkNerd",
    date: "2026-04-26",
    commentsCount: 140,
    content: "Testing speeds up to 1Tbps! How will this change the landscape of remote work and edge computing?",
    hot: true,
    comments: [
      {
        id: "c1",
        author: "LatencyHater",
        date: "2026-04-26",
        text: "Can't wait to play games with 1ms latency!",
      },
    ],
  },
];
